name: Update Documentation

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: "[Setup] Checkout Repository"
      uses: actions/checkout@v1

    - name: "[Setup] Install docfx"
      run: choco install -y docfx

    - name: "[Build] Build Documentation"
      run: docfx docs/docfx.json

    - name: "[Upload] Upload Documentation Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path : docs/_site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: "[Download] Download Documentation Artifact"
      uses: actions/download-artifact@v1
      with:
        name: docs
        path: /docs

    - name: "[Deploy] to GitHub Pages"
      uses: "maxheld83/ghpages@v0.2.1"
      with:
        BUILD_DIR: "/docs"
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}`
