name: Update Documentation

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: "[Setup] Checkout Repository"
      uses: actions/checkout@v1

    - name: "[Setup] Install docfx"
      run: choco install -y docfx

    - name: "[Build] Build Documentation"
      run: docfx docs/docfx.json

    - name: "[Deploy] to GitHub Pages"
      uses: "maxheld83/ghpages@v0.2.1"
      with:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: "docs/_site/"
