name: Update Documentation

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: "[Setup] Checkout Repository"
      uses: actions/checkout@v1

    - name: "[Setup] Ensure 'master' branch exists"
      run: |
        git fetch --tags
        git branch --create-reflog master origin/master

    - name: "[Setup] Install docfx"
      run: choco install -y docfx

    - name: "[Build] Build Documentation"
      run: docfx docs/docfx.json

    - name: "[Upload] Upload Documentation Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path : docs/_site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: "[Download] Download Documentation Artifact"
      uses: actions/download-artifact@v1
      with:
        name: docs

    - name: "[Deploy] Deploy to GitHub Pages"
      run: |
        # Setup
        cd docs
        REMOTE_REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        REPONAME="$(echo $GITHUB_REPOSITORY| cut -d'/' -f 2)"
        REMOTE_BRANCH=gh-pages
        # Prepare Repository
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        git commit -m "Deploy to GitHub Pages";
        # Push
        git push --force $REMOTE_REPO master:$REMOTE_BRANCH
        curl -XPOST -H"Authorization: token ${GITHUB_TOKEN}" -H"Accept: application/vnd.github.mister-fantastic-preview+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/pages/builds && \ # https://git.io/fjsFk
        # Cleanup
        rm -rf .git
        cd $GITHUB_WORKSPACE
